spring:
  cloud:
    gateway:  
      routes:
        - id: department-service
          uri: lb://DEPARTMENT-SERVICE
          predicates:
          - Path=/api/departments/**

        - id: employee-service
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/api/employees/**
        
server:
  port: 7000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

