spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${EMPLOYEE_DB_NAME:employeedb}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:Mysql@254}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

department-service-host-url: ${DEPARTMENT_SERVICE_HOST_URL:http://DEPARTMENT-SERVICE}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true



